# Generated by Django 5.1.5 on 2025-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='photo',
        ),
        migrations.AlterModelOptions(
            name='analysis',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='analysis_details',
        ),
        migrations.AddField(
            model_name='analysis',
            name='historical_inference_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='historical_inference_possible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysis',
            name='photoName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='photo_id',
            field=models.CharField(default='photo1234', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='risk_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sns_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysis',
            name='uploadTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='analysis',
            table='analysis',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
