# Generated by Django 5.1.5 on 2025-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_analysis_photoname_remove_analysis_photourl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='photo_id',
            new_name='photoId',
        ),
        migrations.AddField(
            model_name='analysis',
            name='uploadTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='userId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
